### ISSUE TITLE
Understanding of CTest rewrite and metadata

### ISSUE THREAD

**Issue by nikhil96sher** [xlab-uiuc/IDoCT#17]
Hi,
I was trying to understand the existing re-written ctests and see if my understanding of ctests is correct or not.
I see that there are ctest rewrites for tests like:
1. https://github.com/xlab-uiuc/IDoCT/blob/main/hadoop/test_rewrite/org.apache.hadoop.ipc.TestIdentityProviders.patch
2. https://github.com/xlab-uiuc/IDoCT/blob/main/hadoop/test_rewrite/org.apache.hadoop.crypto.key.kms.TestLoadBalancingKMSClientProvider.patch

But, for these test names, I do not see any entry in `ctest_metadata` file. The same tests also do not have an entry in the mapping file. Does that mean they do not exercise any configuration parameters? And if so, then why are ctests re-written for these?

Also, in terms of `ctest_metadata`, although the number of overall tests are in the order of ~2.5k, the number of unique tests in `ctest_metadata` are only limited to 19. Is it mostly that ctests haven't been ported for other tests or is there any other reason/limitation? This would help in shortlisting the tests for which I can implement the ctests?

**Comment by Alex-Lian** [comment]
> But, for these test names, I do not see any entry in ctest_metadata file. 

Because the ctest_metadata file is constantly being filled. This is a task for students in Software Engineering education and REU program. 

> The same tests also do not have an entry in the mapping file. 

What do you mean by "do not have an entry in the mapping file"? Which mapping file did you search in?

**Comment by nikhil96sher** [comment]
> Because the ctest_metadata file is constantly being filled. This is a task for students in Software Engineering education and REU program.

I see. That makes sense.

> What do you mean by "do not have an entry in the mapping file"? Which mapping file did you search in?

I checked the JSON file at https://github.com/xlab-uiuc/IDoCT/blob/main/generate_mapping/results/hadoop-common/param_unset_getter_map.json

I do see the `testTokenServiceCreationWithLegacyFormat` as a test in the mapping file. But I do not see the `testPluggableIdentityProvider` test.

**Comment by Alex-Lian** [comment]
Thanks for the questions @nikhil96sher and @darko-marinov has responded to you via email. I will close this issue now. But feel free to reopen it if you still have questions @nikhil96sher.
