### ISSUE TITLE
Understanding ctest_metadata.csv structure for multiparameter runs

### ISSUE THREAD

**Issue by NK-Nikunj** [xlab-uiuc/IDoCT#20]
Hi, I ran the `run_ctest.py` script with two parameters (the second parameter value is only considered when the first parameter is true). How do I report such cases with GOOD|PASS or BAD|FAIL within _ctest_metadata.csv_?

**Comment by Alex-Lian** [comment]
Thanks for the questions @NK-Nikunj  and @darko-marinov has responded to you via email. I will close this issue now. But feel free to reopen it if you still have questions @NK-Nikunj.
